
package de03CuoiKi;

import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Form extends javax.swing.JFrame {
    ArrayList<SinhVienATTT> listsvat = new ArrayList<>();
    ArrayList<SinhVienMatMa> listsvmm = new ArrayList<>();
    
    public boolean checkMaSV(String maSV) {
        for(SinhVienATTT s : listsvat) {
            if(s.maSV.equals(maSV)) return false; 
        }
        for(SinhVienMatMa s : listsvmm) {
            if(s.maSV.equals(maSV)) return false; 
        }
        return true;
    }
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cbLoaiSV = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiemTB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDonVi = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Form nhập thông tin Sinh Viên");

        cbLoaiSV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbLoaiSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinh viên an toàn", "Sinh viên mật mã" }));
        cbLoaiSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiSVActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã Sinh Viên: ");

        txtMaSV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Họ Tên: ");

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ngày Sinh: ");

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Điểm TB:");

        txtDiemTB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Học Phí: ");

        txtHocPhi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Đơn Vị: ");

        txtDonVi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Lương: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Giới Tính: ");

        buttonGroup1.add(rbNam);
        rbNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbNam.setSelected(true);
        rbNam.setText("Nam");

        buttonGroup1.add(rbNu);
        rbNu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbNu.setText("Nữ");

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSave.setText("Lưu dữ liệu vào file");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80)
                        .addComponent(txtMaSV))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(cbLoaiSV, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLuong)
                            .addComponent(txtDonVi)
                            .addComponent(txtHocPhi)
                            .addComponent(txtDiemTB)
                            .addComponent(txtHoTen)
                            .addComponent(txtNgaySinh)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbNam)
                                .addGap(61, 61, 61)
                                .addComponent(rbNu)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLoaiSV)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaSV)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHoTen)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNgaySinh)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiemTB)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHocPhi)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDonVi)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLuong)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbNam)
                        .addComponent(rbNu)))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, validateForm(cbLoaiSV.getSelectedIndex()));
        int select = cbLoaiSV.getSelectedIndex();
        String validate = validateForm(select);
        if(!validate.equals("")) {
            JOptionPane.showMessageDialog(this, validate);
            return;
        }
        try {
            if(select == 0) {
                String maSV = txtMaSV.getText();
                String hoTen = txtHoTen.getText();
                String ngaySinh = txtNgaySinh.getText();
                String gioiTinh = rbNam.isSelected() ? "Nam" : "Nữ";
                float diemTB = Float.parseFloat(txtDiemTB.getText());
                float hocPhi = Float.parseFloat(txtHocPhi.getText());
                FileOutputStream fos = new FileOutputStream("sinhvienhattt.dat", true);
                OutputStreamWriter ops = new OutputStreamWriter(fos, "UTF-8");
                BufferedWriter bw = new BufferedWriter(ops);
                SinhVienATTT svattt = new SinhVienATTT(hocPhi, maSV, hoTen, ngaySinh, gioiTinh, diemTB);
                bw.write(svattt.toString());
                bw.newLine();
                
                bw.close();
                ops.close();
                fos.close();
                JOptionPane.showMessageDialog(this, "Lưu thành công");
                listsvat.add(svattt);
                resetForm();
            } else {
                String maSV = txtMaSV.getText();
                String hoTen = txtHoTen.getText();
                String ngaySinh = txtNgaySinh.getText();
                String gioiTinh = rbNam.isSelected() ? "Nam" : "Nữ";
                float diemTB = Float.parseFloat(txtDiemTB.getText());
                String donVi = txtDonVi.getText();
                float luong = Float.parseFloat(txtLuong.getText());
                FileOutputStream fos = new FileOutputStream("sinhvienmm.dat", true);
                OutputStreamWriter ops = new OutputStreamWriter(fos, "UTF-8");
                BufferedWriter bw = new BufferedWriter(ops);
                SinhVienMatMa svmm = new SinhVienMatMa(donVi, luong, maSV, hoTen, ngaySinh, gioiTinh, diemTB);
                bw.write(svmm.toString());
                bw.newLine();
                
                bw.close();
                ops.close();
                fos.close();
                JOptionPane.showMessageDialog(this, "Lưu thành công");
                listsvmm.add(svmm);
                resetForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi file");
            return;
        }
         
    }//GEN-LAST:event_btnSaveActionPerformed

    public String validateForm(int select) {
        if(txtMaSV.getText().equals("") || 
            txtHoTen.getText().equals("") ||
            txtNgaySinh.getText().equals("") ||
            txtDiemTB.getText().equals("") ||
            (select == 0 ? txtHocPhi.getText().equals("") : (txtDonVi.getText().equals("") || txtLuong.getText().equals("")) )
        ) {
            return "Không được để trống trường nào";
        }
        if(!checkMaSV(txtMaSV.getText())) return "Đã có mã SV này vui lòng chọn mã SV khác.";
        String regexNgaySinh = "^([0-2][0-9]||3[0-1])/(0[0-9]||1[0-2])/([0-9][0-9])?[0-9][0-9]$";
        if(!txtNgaySinh.getText().matches(regexNgaySinh)) return "Ngày sinh không hợp lệ (VD: 06/06/2001).";
        try {
            if(select == 0) {
                float x = Float.parseFloat(txtHocPhi.getText());
            } else {
                float x = Float.parseFloat(txtDiemTB.getText());
                float y = Float.parseFloat(txtLuong.getText());
            }
        } catch (NumberFormatException e) {
            return "Định dạng kiểu sai Vui lòng nhập lại các trường số.";
        }
        return "";
    }
    
    private void cbLoaiSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiSVActionPerformed
        // TODO add your handling code here:
        if(cbLoaiSV.getSelectedIndex() == 0) {
            txtHocPhi.setVisible(true);
            txtDonVi.setVisible(false);
            txtLuong.setVisible(false);
        } else if(cbLoaiSV.getSelectedIndex() == 1) {
            txtHocPhi.setVisible(false);
            txtDonVi.setVisible(true);
            txtLuong.setVisible(true);
        }
        resetForm();
    }//GEN-LAST:event_cbLoaiSVActionPerformed

    public void resetForm() {
        txtMaSV.setText("");
        txtHoTen.setText("");
        txtNgaySinh.setText("");
        txtDiemTB.setText("");
        txtHocPhi.setText("");
        txtDonVi.setText("");
        txtLuong.setText("");
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbLoaiSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTextField txtDiemTB;
    private javax.swing.JTextField txtDonVi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtNgaySinh;
    // End of variables declaration//GEN-END:variables
}
